changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - enhancement

    - title: Breaking Changes 🛠
      labels:
        - breaking-change

    - title: Bug Fix 🐛
      labels:
        - bug

    - title: Other Changes
      labels:
        - "*"
