exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']

- repo: local
  hooks:
    - id: isort
      name: isort
      language: system
      entry: uv run isort .
      require_serial: true
      types_or: [cython, pyi, python]

- repo: local
  hooks:
    - id: black
      name: black (code formatting)
      language: system
      entry: uv run black
      types: [python]

- repo: local
  hooks:
    - id: flake8
      name: flake8 (code linting)
      language: system
      entry: uv run flake8
      types: [python]

- repo: local
  hooks:
  - id: mypy
    name: mypy (static typing)
    pass_filenames: false
    language: system
    entry: uv run poe type-check
    verbose: true
